name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Linux builds
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64
          # macOS builds
          - os: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }}" \
            -o ripeatlas-${{ matrix.os }}-${{ matrix.arch }}

      - name: Generate checksums
        run: |
          sha256sum ripeatlas-${{ matrix.os }}-${{ matrix.arch }} > ripeatlas-${{ matrix.os }}-${{ matrix.arch }}.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ripeatlas-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            ripeatlas-${{ matrix.os }}-${{ matrix.arch }}
            ripeatlas-${{ matrix.os }}-${{ matrix.arch }}.sha256

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release files
        run: |
          mkdir release-files
          find artifacts -type f -exec cp {} release-files/ \;
          cd release-files
          sha256sum * > SHA256SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
